# Generated by Django 5.2.2 on 2025-06-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carro',
            options={'ordering': ['marca', 'modelo', '-ano']},
        ),
        migrations.AlterModelOptions(
            name='critica',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.PositiveIntegerField(verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='marca',
            field=models.CharField(default='Desconhecida', max_length=40, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.CharField(max_length=40, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='critica',
            name='texto',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterUniqueTogether(
            name='carro',
            unique_together={('marca', 'modelo', 'ano')},
        ),
    ]
