# Generated by Django 5.2.2 on 2025-06-07 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_carro_options_alter_critica_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='critica',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Crítica', 'verbose_name_plural': 'Críticas'},
        ),
        migrations.AlterField(
            model_name='critica',
            name='avaliacao',
            field=models.IntegerField(verbose_name='Avaliação (1 a 5)'),
        ),
        migrations.AlterField(
            model_name='critica',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criticas', to='reviews.carro', verbose_name='Carro'),
        ),
        migrations.AlterField(
            model_name='critica',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='critica',
            name='texto',
            field=models.TextField(max_length=2000, verbose_name='Texto da crítica'),
        ),
        migrations.AlterField(
            model_name='critica',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criticas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
