# Generated by Django 5.2.2 on 2025-06-17 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_critica_options_alter_critica_avaliacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarroImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EX', 'Exterior'), ('IN', 'Interior'), ('MO', 'Motor')], max_length=2, verbose_name='Tipo')),
                ('foto', models.ImageField(upload_to='carros', verbose_name='Foto')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='reviews.carro', verbose_name='Carro')),
            ],
            options={
                'verbose_name': 'Imagem de carro',
                'verbose_name_plural': 'Imagens de carro',
                'ordering': ['carro', 'tipo'],
                'unique_together': {('carro', 'tipo')},
            },
        ),
    ]
